[global]
dataFrameSerialization = "legacy"

[logger]
level = "info"

[client]
showErrorDetails = false
toolbarMode = "minimal"

[runner]
magicEnabled = false
installTracer = false
fixMatplotlib = true

[server]
runOnSave = false
allowRunOnSave = false
port = 8501
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200
maxMessageSize = 200
enableWebsocketCompression = false

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[theme]
primaryColor = "#2E8B57"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif" 